# Generated by Django 5.0.6 on 2024-05-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Company Name')),
                ('official_name', models.CharField(max_length=250, verbose_name='Official Name')),
                ('brand_name', models.CharField(max_length=250, verbose_name='Brand Name')),
                ('sector_category', models.CharField(max_length=250, verbose_name='Sector Category')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('phone', models.CharField(max_length=250, verbose_name='Phone')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('faks', models.CharField(max_length=250, verbose_name='Faks')),
                ('city_code', models.CharField(max_length=250, verbose_name='City Code')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Is Checked by Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic Company',
                'verbose_name_plural': 'Clinic Companies',
            },
        ),
    ]
